### ISSUE TITLE
Bridging headers for Swift

### ISSUE THREAD

**Issue by kermankohli** [onesky/plugin-ios-ota#10]
I can't use this library on Swift because it says that the OneSkyOTAPlugin module can't be found - presumably because there's no bridging headers.

**Comment by bretdabaker** [comment]
To use the plugin for Swift you should create one single Objective-C bridging header and add `#import <OneSkyOTAPlugin/OneSkyOTAPlugin.h>` along with other Objective-C imports there.

Please read the [documentation](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html) for more details.

**Comment by kermankohli** [comment]
I would have assumed that a SDK for a product would provide Swift support natively?

**Comment by bretdabaker** [comment]
You can mix and match Swift and Objective-C in the same project, one simply won't write a library in Objective-C and rewrite it in Swift, vice versa. 

If you develop in Swift you can not avoid using libraries written in Objective-C, so please read the documentation and learn how to use the bridging header.

**Comment by kermankohli** [comment]
I don't think you really understood what I said. All I said was that if you're making a SDK for developers, you should have things like bridging headers included so that Swift compatibility is enabled by default.

**Comment by bretdabaker** [comment]
The bridging header should be created for the project and includes ALL Objective-C files and libraries, not just one library. 

Even if a header was provided you still need to configure the Build Settings to make it work, you can't declare multiple bridging headers in Build Settings so what you are asking simply doesn't make sense for a library written in Objective-C.

Usually the name of the bridging header includes the name of the project. This step is expected to be done by the project owner.

You can find more detail here:
http://stackoverflow.com/a/24005242

**Comment by kermankohli** [comment]
OSLocalizedString doesn't work in Swift because of #define....

**Comment by bretdabaker** [comment]
It's okay, let me add swift integration guide to README.md later. Will also checkout the macro.

**Comment by kermankohli** [comment]
Thanks! I really need the plugin soon though :p

**Comment by bretdabaker** [comment]
You can still use the plugin without the macro.

```
OneSkyOTAPlugin.localizedStringForKey("key", value: "value", table: "tableName")
```

**Comment by kermankohli** [comment]
Is there a macro without the table property and comment instead of "value"?

OneSkyOTAPlugin.localizedStringForKey("key", comment: "value")

**Comment by bretdabaker** [comment]
You can use public functions to wrap the code, here is the file with the macros:

[OneSkyOTAPlugin.swift.zip](https://github.com/onesky/plugin-ios-ota/files/57593/OneSkyOTAPlugin.swift.zip)

**Comment by danielkiedrowski** [comment]
Swift 3 needs to be like this:

```swift
public func OSLocalizedString(_ key: String, comment: String) -> String {
    return OneSkyOTAPlugin.localizedString(forKey: "key", value: "", table: nil)
}

public func OSLocalizedStringFromTable(_ key: String, table: String, comment: String) -> String {
    return OneSkyOTAPlugin.localizedString(forKey: "key", value: "", table: table)
}
```
