### ISSUE TITLE
Does not work with line breaks at all

### ISSUE THREAD

**Issue by Tibbs** [onesky/plugin-ios-ota#11]
Hi,

When a phrase has line breaks "\n" this plug in does not work at all.

**Comment by bretdabaker** [comment]
Hi, what do you mean by doesn't work? The line break is missing? Or the app crashed?

Please provide more information for us to debug.

Thanks!

**Comment by Tibbs** [comment]
does not do any translation, it just uses the default

**Comment by Tibbs** [comment]
for example this does not work: "Line one\nLine two" but this one does "Line one. Line Two"
It simple does not download/update the translation if there is a line break in the string. I think it ignores it or treat it as a different string.

**Comment by bretdabaker** [comment]
The problem is caused by our API, our backend engineer is working to fix the problem. Will let you know once it's fixed.

**Comment by bretdabaker** [comment]
The bug has been fixed, please let us know if the problem persists.
