### ISSUE TITLE
Locale mismatch

### ISSUE THREAD

**Issue by stephenkopylov** [onesky/plugin-ios-ota#13]
Hello, our company uses your plugin and it works like charm!

But some time ago I open issue with onesky xcode plugin:
https://github.com/onesky/plugin-xcode/issues/26

So, question is: 
will ota-framework download correct locale version (hi) if I change it from "hi-IN" to "hi"?

**Comment by bretdabaker** [comment]
The OTA plugin does download the correct locale version (hi) as it uses a different API.

**Comment by stephenkopylov** [comment]
Thank you :)
