### ISSUE TITLE
OTA downloaded files included in iCloud backups

### ISSUE THREAD

**Issue by RetepV** [onesky/plugin-ios-ota#18]
Hi,

Our app was recently rejected because we were storing too much data in the iCloud backup. So we went through all our files, to see what was marked for Exclude From Backup, and what not.

Amongst the files that are included in the backup, there is OneSkyStrings.plist. This file is downloaded by this OTA plugin and stored in the Documents folder of the app.

This file should not be included in iCould backups, as it can be easily regenerated after iOS decides to delete it. So it either needs to be stored in the Library/Caches folder, or it needs to be saved and marked with the 'NSURLIsExcludedFromBackupKey' file resource property set to YES. Will that be possible?

Please check out this: https://developer.apple.com/library/ios/qa/qa1719/_index.html

Cheers!
Peter

**Comment by bretdabaker** [comment]
Will add support for that soon.

**Comment by bretdabaker** [comment]
Fixed in [0.9.12](https://github.com/onesky/plugin-ios-ota/releases/tag/0.9.12)

**Comment by RetepV** [comment]
Thanks! Great work!
