### ISSUE TITLE
OneSky Log

### ISSUE THREAD

**Issue by albi00** [onesky/plugin-ios-ota#2]
How can i disable all log from OneSkyOTAPlugin?

Thanks!
A.

**Comment by bretdabaker** [comment]
@albi00 I have added option to disable debug log:
https://github.com/onesky/plugin-ios-ota/releases/tag/0.8.4

**Comment by albi00** [comment]
It works, thanks!!

A.

**Comment by Micke5** [comment]
Hi! How do I set the option to disable debug logs?
