### ISSUE TITLE
NSLocalizedStringFromTableInBundle support

### ISSUE THREAD

**Issue by qclmnt** [onesky/plugin-ios-ota#24]
Hi do you guys planned to support `NSLocalizedStringFromTableInBundle` ?

**Comment by bretdabaker** [comment]
This method uses local `NSBundle` directly, by supporting `NSLocalizedStringFromTableInBundle` do you mean having the plugin fallbacks to specific bundle if the plugin fails to load translations from OneSky?

**Comment by qclmnt** [comment]
We need it to force a language translation some times :


Like this :
```
NSString *forcedBundleString = bundleString;
    NSBundle *bundle = [NSBundle bundleWithPath:[[NSBundle mainBundle] pathForResource:forcedBundleString ofType:@"lproj"]];
    return NSLocalizedStringFromTableInBundle(([NSString stringWithFormat:@"******.%@",language]), nil, bundle, nil);
```

**Comment by siburb** [comment]
@bretdabaker We could do with this too. We use `NSLocalizedStringFromTableInBundle` for accessing localized strings within our internal pods.

**Comment by rubyluk** [comment]
Fixed in https://github.com/onesky/plugin-ios-ota/releases/tag/0.10.1
