### ISSUE TITLE
Add Multiple Debug/Log Levels

### ISSUE THREAD

**Issue by keithbhunter** [onesky/plugin-ios-ota#27]
By default, debug is true and logs go to the console. The problem is that this makes the console unreadable because there will be thousands of message that just say "Found translation for..." Having multiple log levels would be nice, specifically a level that prints the checking for update, translations downloaded, and translation download errors without printing each of the translation lookups.

**Comment by rubyluk** [comment]
Fixed in https://github.com/onesky/plugin-ios-ota/releases/tag/0.10.1
