### ISSUE TITLE
Switch to https to support App Transport Security

### ISSUE THREAD

**Issue by detouch** [onesky/plugin-ios-ota#4]
**Problem:**
In iOS 9, an app must use TLS for all http traffic.
https://developer.apple.com/library/prerelease/ios/releasenotes/General/WhatsNewIniOS/Articles/iOS9.html#//apple_ref/doc/uid/TP40016198-SW14

Otherwise, all non-secure connections must be declared as exceptions.
Without declaring the onesky host(s) as an exception, OTA phrase updates do not work.

**Suggested solution:**
Please switch to https/TLS for a simple integration without declaring security exceptions.

**Comment by quekshuy** [comment]
+1

**Comment by bretdabaker** [comment]
@detouch @quekshuy The connections have always been via HTTPS, our api server supports TLS 1.2 and I can run the demo without any exception under iOS 9 Beta (both simulator and device). Am I missing something?

**Comment by detouch** [comment]
You are right @bretdabaker, I apologize for the false alarm: OTA works flawlessly on iOS 9.
I should not have raised an issue just because a fellow developer complained ;-)
