### ISSUE TITLE
iOS 9 bugs, possible solution

### ISSUE THREAD

**Issue by Silkjaer** [onesky/plugin-ios-ota#7]
We have people reporting errors after upgrading to iOS 9.

Localization abbreviation has changed, e.g. Danish was in iOS 8 and previous "da", but is in iOS 9 da-DK.

NSLocalizedString works as expected – it probably checks "da-DK" first and falls back to "da". Could this be implemented in OneSkyOTAPlugin.localizedStringForKey? 

I imagine a fallback routine as follows:

1. check for "da-DK"
2. check for "da"
3. check NSLocalizedString (for local strings)
4. fallback to "en"

Now it seems it does as follows:

1. check for "da-DK"
2. fallback to "en"

**Comment by bretdabaker** [comment]
Thanks for reporting the bug, will look into it.

**Comment by paolocolombo** [comment]
hi,
it's a avery annoying bug.
Have you established a date for the resolution or shall we find a workaround?

**Comment by bretdabaker** [comment]
Will release a fix within 48 hours, right now you can duplicate the strings from dk to dk-DK on OneSky web admin so that it works on iOS 9.

**Comment by paolocolombo** [comment]
Hi bretdabaker,
thanks for your precious feedback!
Have a nice day.

**Comment by bretdabaker** [comment]
Fixed in [0.9.3](https://github.com/onesky/plugin-ios-ota/releases/tag/0.9.3)
