### ISSUE TITLE
Bitcode issues

### ISSUE THREAD

**Issue by Silkjaer** [onesky/plugin-ios-ota#9]
bitcode bundle could not be generated because '/[removed]/OneSkyOTAPlugin/libOneSkyOTAPlugin.a(OneSkyOTAPlugin.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

**Comment by bretdabaker** [comment]
Fixed in https://github.com/onesky/plugin-ios-ota/releases/tag/0.9.5

I have tested creating archives on Xcode 6.4 and Xcode 7.1.
